// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package store

import (
	"github.com/go-redis/redis"
	"github.com/gorilla/sessions"
	"github.com/the-bailiff/bailiff/internal/config"
)

// Injectors from wire.go:

func redisStoreImpl() (sessions.Store, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	redisOptions := provideRedisOptions(configConfig)
	client := redis.NewClient(redisOptions)
	storeOptions, err := provideOptions(configConfig)
	if err != nil {
		return nil, err
	}
	store, err := provideRedisStore(client, storeOptions, configConfig)
	if err != nil {
		return nil, err
	}
	return store, nil
}
